In [1]:
import torch
import torch.nn as nn
import numpy as np

import matplotlib.pyplot as plt

# Softmax

In [2]:
logits = 10 * ( torch.rand((2,5)) - 0.5 )

softmax = nn.Softmax(dim=1)

p_vector = softmax(logits)  

print('Input Logits \n', logits,'\n')
print('Softmax Output \n', p_vector,'\n')
print('Sum of Softmax Output \n ', torch.sum(p_vector,axis=1))

Input Logits 
 tensor([[-0.4072,  0.7402,  2.5964,  3.8201, -0.7910],
        [ 0.2692,  0.7671, -1.7903, -1.4712,  4.1446]]) 

Softmax Output 
 tensor([[0.0107, 0.0337, 0.2156, 0.7328, 0.0073],
        [0.0195, 0.0322, 0.0025, 0.0034, 0.9424]]) 

Sum of Softmax Output 
  tensor([1., 1.])


# Softmax in Dense Layer

In [3]:
n_data = 8
n_feature = 5 
n_class = 6

logits = 10 * ( torch.rand((n_data,n_feature)) - 0.5 )
model = nn.Sequential(
            nn.Linear(n_feature,n_class),
            nn.Softmax(dim=1)
)

output = model(logits)
print(output)

tensor([[1.7258e-02, 1.3010e-01, 6.8685e-01, 1.2988e-01, 2.2537e-02, 1.3371e-02],
        [5.0495e-01, 3.9171e-02, 4.2723e-03, 3.1348e-01, 3.3819e-02, 1.0430e-01],
        [7.5292e-02, 1.8671e-01, 1.3505e-01, 2.2297e-02, 4.6675e-01, 1.1390e-01],
        [2.8586e-01, 8.3367e-02, 2.4353e-01, 1.4939e-01, 7.3324e-02, 1.6452e-01],
        [1.6620e-01, 5.3034e-03, 3.7374e-02, 7.3499e-01, 2.8760e-04, 5.5846e-02],
        [1.6161e-02, 4.3445e-02, 6.5368e-01, 1.2507e-03, 1.1440e-01, 1.7106e-01],
        [2.0685e-01, 2.4858e-01, 1.8740e-01, 5.2040e-02, 8.5754e-02, 2.1937e-01],
        [7.1589e-02, 2.4863e-01, 6.6761e-02, 6.6869e-03, 4.2098e-01, 1.8536e-01]],
       grad_fn=<SoftmaxBackward>)


# Multiclass  Classifier

In [4]:
class testModel(nn.Module):
    def __init__(self,i_feature,o_feature):
        super(testModel, self).__init__()
        
        self.fc1 = nn.Linear(n_feature, 8)
        self.fc2 = nn.Linear(8, 5)
        self.fc3 = nn.Linear(5, o_feature )
        self.softmax = nn.Softmax(dim=1)
        self.relu = nn.ReLU()
        
    def forward(self, x):
        print('input shape : ', x.shape)
        x = self.fc1(x)
        x = self.relu(x)
        print('Layer1 Output shape : ', x.shape)
        x = self.fc2(x)
        x = self.relu(x)
        print('Layer2 Output shape : ', x.shape)
        x = self.fc3(x)
        x = self.softmax(x)
        print('output shape : ', x.shape)
        return x
    
n_feature = 5
n_class   = 3
logits = 10 * ( torch.rand((8,n_feature)) - 0.5 )

model = testModel(n_feature, n_class)
y = model.forward(logits)
print(y)
print()
print(torch.sum(y, axis=1))

input shape :  torch.Size([8, 5])
Layer1 Output shape :  torch.Size([8, 8])
Layer2 Output shape :  torch.Size([8, 5])
output shape :  torch.Size([8, 3])
tensor([[0.3742, 0.4250, 0.2008],
        [0.3799, 0.3535, 0.2665],
        [0.3671, 0.3704, 0.2625],
        [0.3262, 0.3512, 0.3225],
        [0.3640, 0.4318, 0.2041],
        [0.3669, 0.4095, 0.2236],
        [0.3731, 0.4059, 0.2210],
        [0.3071, 0.3439, 0.3490]], grad_fn=<SoftmaxBackward>)

tensor([1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000],
       grad_fn=<SumBackward1>)
