## Shape of Dense Layer

In [1]:
import torch
import torch.nn as nn
import numpy as np

N, n_feature = 4, 10

x = torch.rand((N, n_feature))

n_neuron = 3 # number of output features

dense = nn.Linear(n_feature, n_neuron)
activation = nn.Sigmoid()

weight, bias = dense.weight, dense.bias

y_torch = activation(dense(x))                     # X @ W.T + B = Y

print('input  shape         : ', x.shape)            # [ Batch size, input Feature]
print('weight shape         : ', weight.shape) # Row Vector!
print('bias   shape         : ', bias.shape)   # Row Vector!
print('output shape (torch) : ', y_torch.shape)      # [ Batch size, output Feature]
print('output       (torch) \n', y_torch)

input  shape         :  torch.Size([4, 10])
weight shape         :  torch.Size([3, 10])
bias   shape         :  torch.Size([3])
output shape (torch) :  torch.Size([4, 3])
output       (torch) 
 tensor([[0.4873, 0.3589, 0.2913],
        [0.3683, 0.2880, 0.2570],
        [0.4203, 0.3150, 0.2472],
        [0.3819, 0.3107, 0.2445]], grad_fn=<SigmoidBackward>)


In [2]:
y = x @ weight.T + bias
y = y.detach().numpy()
y_numpy = 1 / (1 + np.exp(-y))
print('output shape (torch) : ', y_numpy.shape)
print('output       (numpy) \n', y_numpy)

output shape (torch) :  (4, 3)
output       (numpy) 
 [[0.48725018 0.3588789  0.2913365 ]
 [0.36830077 0.28803453 0.25700906]
 [0.4203049  0.31497717 0.2472047 ]
 [0.38185033 0.31068537 0.24446833]]


In [3]:
x = x.detach().numpy()
w = weight.detach().numpy()
b = bias.detach().numpy()

In [4]:
print('input  shape         : ', x.shape)   # [ Batch size, input Feature]
print('weight shape         : ', w.shape)   # Row Vector!
print('bias   shape         : ', b.shape)   # Row Vector!

y = np.zeros((N,n_neuron))

for i in range(N):
    temp_x = x[i]
    for j in range(n_neuron):
        temp_w = w[j]
        y_temp = np.sum(temp_x * temp_w) + b[j]
        y[i][j] = 1 / (1 + np.exp(-y_temp))
        
print('output shape (numpy) : ', y.shape)
print('output       (numpy) \n', y)

input  shape         :  (4, 10)
weight shape         :  (3, 10)
bias   shape         :  (3,)
output shape (numpy) :  (4, 3)
output       (numpy) 
 [[0.48725017 0.3588789  0.2913365 ]
 [0.36830077 0.28803454 0.25700906]
 [0.42030491 0.31497717 0.24720471]
 [0.38185033 0.31068536 0.24446833]]
