# Average Pooling / Max Pooling

### 1D 

#### Average Pooling 
<br>
<font size="5">
    $$ p[i] = \frac{1}{2s+1}\sum_{\alpha=i-s}^{i+s} w[\alpha] $$
</font>


<br>
<font size="5">
    $$ L_{o} = L_{i} - L_{p} + 1 $$
</font>

<br>

#### Max Pooling 

<br>
<font size="5">
    $$ p[i] = max(W_{i}) $$
</font>


<br>
<font size="5">
    $$ L_{o} = L_{i} - L_{p} + 1 $$
</font>

### 2D

#### Average Pooling 

<br>
<font size="5">
    $$ p[i,j] = \frac{1}{(2s+1)(2t+1)}
    \sum_{\alpha=i-s}^{i+s}
    \sum_{\beta=j-t}^{j+t}
    w[\alpha, \beta] $$
</font>

<br>
<font size="5">
    $$ L_{o} = L_{i} - L_{p} + 1 $$
</font>

#### Max Pooling 

<br>
<font size="5">
    $$ p[i,j] = max(W_{i,j}) $$
</font>


<br>
<font size="5">
    $$ L_{o} = L_{i} - L_{p} + 1 $$
</font>

In [5]:
import numpy as np

# 1D Average Pooling

# Window Size
win_size = 3

# random data
data = np.random.randint(0,10,(10,))
data_len = len(data)
print("Input data: ", data)
print("Length of data: ", data_len, '\n')\

out_len = data_len - (win_size - 1)

# average pooling
output = np.zeros((out_len,))
for idx in range(out_len):
    output[idx] = np.mean(data[idx:idx+win_size])

print("Pooled data: ", np.round(output,2))
print("Length of pooled data: ", len(output))

Input data:  [7 3 6 2 3 9 9 3 0 8]
Length of data:  10 

Pooled data:  [5.33 3.67 3.67 4.67 7.   7.   4.   3.67]
Length of pooled data:  8


In [6]:
# 1D Max Pooling

# Window Size
win_size = 3

# random data
data = np.random.randint(0,10,(10,))
data_len = len(data)
print("Input data: ", data)
print("Length of data: ", data_len, '\n')\

out_len = data_len - (win_size - 1)

# Max pooling
output = np.zeros((out_len,))
for idx in range(out_len):
    output[idx] = np.max(data[idx:idx+win_size])

print("Pooled data: ", np.round(output,2))
print("Length of pooled data: ", len(output))

Input data:  [9 1 2 9 9 6 2 6 8 4]
Length of data:  10 

Pooled data:  [9. 9. 9. 9. 9. 6. 8. 8.]
Length of pooled data:  8


In [7]:
# 2D Average Pooling

# Window Size
window_size = 3 # 3x3

# generate 2D data
H, W = 5, 5
data = np.random.randint(0,5,(H,W))
print(data)
print('=====')

# Output
output_H, output_W = H - (window_size - 1), W - (window_size - 1)

output = np.zeros((output_H,output_W))
for h in range(output_H):
    for w in range(output_W):
        # extract the window
        window_data = data[h:h+window_size,w:w+window_size]
        output[h,w] = np.mean(window_data)
print('=====')

print(np.round(output,3))

[[0 4 2 3 4]
 [1 0 3 0 1]
 [3 3 1 3 1]
 [1 3 4 4 2]
 [1 2 3 1 4]]
=====
=====
[[1.889 2.111 2.   ]
 [2.111 2.333 2.111]
 [2.333 2.667 2.556]]


In [8]:
# 2D Max Pooling

# Window Size
window_size = 3 # 3x3

# generate 2D data
H, W = 5, 5
data = np.random.randint(0,5,(H,W))
print(data)
print('=====')

# Output
output_H, output_W = H - (window_size - 1), W - (window_size - 1)

output = np.zeros((output_H,output_W))
for h in range(output_H):
    for w in range(output_W):
        # extract the window
        window_data = data[h:h+window_size,w:w+window_size]
        output[h,w] = np.max(window_data)
print('=====')

print(np.round(output,3))

[[3 3 4 2 2]
 [3 3 1 1 0]
 [4 3 2 1 3]
 [0 3 1 3 0]
 [1 1 2 0 4]]
=====
=====
[[4. 4. 4.]
 [4. 3. 3.]
 [4. 3. 4.]]
